name: Preprocess wf

on:
  push:
    paths:
      - 'preprocessing/**'
    branches:
      - master
  pull_request:
    paths:
      - 'preprocessing/**'
    branches:
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install Dependencies
        run: pip install pandas scikit-learn

      - name: Run Preprocessing Script
        run: python preprocessing/automate_arya.py

      - name: Commit and Push Preprocessed Data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"

          if [[ -f preprocessing/titanic_clean.csv ]]; then
            git add preprocessing/titanic_clean.csv
            git diff --staged --quiet || git commit -m "Update preprocessed Titanic dataset"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/Aryadibelorerung/Eksperimen_SML_Arya.git HEAD:master
          else
            echo "Preprocessed data file not found. Skipping commit."
          fi
